"Directory to vim colors: /usr/share/vim/vim74/colors/

let base16colorspace=256  " Access colors present in 256 colorspace
set background=dark

colorscheme base16-default
"colorscheme base16-material-dark
"colorscheme hybrid_material
"colorscheme hybrid_reverse
let g:enable_bold_font=1
