#!/bin/bash

# Amazon
export JAVA_HOME="/Library/Java/JavaVirtualMachines/amazon-corretto-11.jdk/Contents/Home"
export PATH=$HOME/.toolbox/bin:$PATH
export PATH=$BRAZIL_CLI_BIN:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/Users/gazeric/Downloads/jdt-language-server-1.9.0-202203031534/bin:$PATH
# To detect a Python environment
export PATH="/usr/local/opt/python@3.10/libexec/bin:$PATH"
