#!/bin/bash

# Oh my zsh settings
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="random"
# ZSH_THEME_RANDOM_CANDIDATES=(
# "robbyrussell" 
# "agnoster" 
# "kiwi"
# "refined"
# "norm"
# "humza"
#)
zstyle ':omz:update' mode auto      # update automatically without asking
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"
  
plugins=(git
zsh-autosuggestions
history-substring-search
zsh-syntax-highlighting
macos
sudo
zsh-completions
#autojump
vi-mode
)

source $ZSH/oh-my-zsh.sh
